### ISSUE TITLE
add z/OS C/C++ compiler 'native' support

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/cmakeport#12]
Would it make sense to add z/OS C/C++ compilers into Cmake?

https://github.com/Kitware/CMake/tree/master/Modules/Platform lists special support for AIX IBM compilers...

Maybe COBOL, PL/I and HL/ASM could be added too?

**Comment by MikeFultonDev** [comment]
@fanbo-meng would appreciate your thoughts

**Comment by fanbo-meng** [comment]
It would certainly be nice to have if people have such need, but so far by already having a generic `Modules/Platform/OS390.cmake` we haven't seen any need for that at least for the llvm project that we've been working on.

**Comment by MikeFultonDev** [comment]
@perry-ca mentioned that the latest versions of CMake already support this so I think this is 'already done'...

**Comment by perry-ca** [comment]
We (i.e. Fanbo) added the support for the newer compilers in the patch in cmakeport.  I think the XL compiler already had support under the zOS* files. I would like rename these.    That ends up making the compiler called "zOS" in tests of the compiler id and in error messages.   We should rename these files to "XLZOS*" (or something better).  For reference, the other IBM compilers are:
- XLClang.cmake (aix/zos xlclang compilers)
- XL.cmake (aix XL compilers)
- IBMClang.cmake (aix/linux/zos ibm-clang compilers)

The compilers are detected with:
```
>grep _compiler_id_pp_test IBM* XL* zOS*
IBMClang-C-DetermineCompiler.cmake:set(_compiler_id_pp_test "defined(__open_xl__) && defined(__clang__)")
IBMClang-CXX-DetermineCompiler.cmake:set(_compiler_id_pp_test "defined(__open_xl__) && defined(__clang__)")
XL-C-DetermineCompiler.cmake:set(_compiler_id_pp_test "defined(__IBMC__) && !defined(__COMPILER_VER__) && __IBMC__ >= 800")
XL-CXX-DetermineCompiler.cmake:set(_compiler_id_pp_test "defined(__IBMCPP__) && !defined(__COMPILER_VER__) && __IBMCPP__ >= 800")
XLClang-C-DetermineCompiler.cmake:set(_compiler_id_pp_test "defined(__ibmxl__) && defined(__clang__)")
XLClang-CXX-DetermineCompiler.cmake:set(_compiler_id_pp_test "defined(__ibmxl__) && defined(__clang__)")
zOS-C-DetermineCompiler.cmake:set(_compiler_id_pp_test "defined(__IBMC__) && defined(__COMPILER_VER__)")
zOS-CXX-DetermineCompiler.cmake:set(_compiler_id_pp_test "defined(__IBMCPP__) && defined(__COMPILER_VER__)")
```

I think the OEL compiler is falling into the generic Clang.cmake.  We'll need to double check this.
